name: Node.js CI
on:
  push:
    branches:
      - "master"

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm install
      - run: npm run build
      - run: npm test
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          target_branch: gh-pages
          build_dir: build
